package BAB_02;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author WahRadar
 */
public class Kasir extends javax.swing.JFrame {

    public ArrayList menu = new ArrayList();
    public ArrayList harga = new ArrayList();
    public ArrayList qty = new ArrayList();
    public ArrayList subtotal = new ArrayList();

    public Kasir() {
        initComponents();
    }

    // A. METHOD KOSONG
    private boolean cekKosong(boolean makan) {
        boolean hasil = false;

        if (makan == true) {
            if (txtQtyMakan.getText().isEmpty() == true) {
                JOptionPane.showMessageDialog(null, "Qty makanan harus diisi");
                hasil = true;
            }
        } else {
            if (txtQtyMinum.getText().isEmpty() == true) {
                JOptionPane.showMessageDialog(null, "Qty minuman harus diisi");
                hasil = true;
            }
        }
        return hasil;
    }

    // B. METHOD CEK DATA TABEL
    private boolean cekDataTabel(String data) {
        boolean hasil = menu.contains(data);
        if (hasil == true) {
            JOptionPane.showMessageDialog(null, "Menu sudah ditambahkan");
        }
        return hasil;
    }

    // C. METHOD SET HARGA MAKANAN
    private void setHargaMakanan() {
        int harga = 0;
        int pil = cboMakan.getSelectedIndex();
        switch (pil) {
            case 1:
                harga = 25000;
                break;
            case 2:
                harga = 25000;
                break;
            case 3:
                harga = 35000;
                break;
            case 4:
                harga = 35000;
                break;
            case 5:
                harga = 40000;
                break;
        }
        txtHargaMakan.setText("" + harga);
        try {
            int qty = Integer.parseInt(txtQtyMakan.getText());
            txtSubtotalMakan.setText("" + harga * qty);
        } catch (NumberFormatException e) {
            txtSubtotalMakan.setText("0");
        }
    }

    // D. METHOD SET HARGA MINUMAN
    private void setHargaMinuman() {
        int harga;
        if (cboMinum.getSelectedIndex() == 0) {
            harga = 0;
        } else {
            harga = 20000;
        }
        txtHargaMinum.setText("" + harga);
        try {
            int qty = Integer.parseInt(txtQtyMinum.getText());
            txtSubtotalMinum.setText("" + harga * qty);
        } catch (NumberFormatException e) {
            txtSubtotalMinum.setText("0");
        }
    }

    // E. METHOD SET TABEL
    private void setTabel() {
        int total = 0;
        double pajak = 0;
        int bayar = 0;

        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("Menu");
        tbl.addColumn("Qty");
        tbl.addColumn("Harga");
        tbl.addColumn("Sub Total");

        for (int n = 0; n < menu.size(); n++) {
            total = total + Integer.parseInt(subtotal.get(n).toString());

            tbl.addRow(new Object[]{
                menu.get(n),
                qty.get(n),
                harga.add(n),
                subtotal.get(n),});
        }

        pajak = total * 0.1;
        bayar = (int) (total + pajak);

        tableData.setModel(tbl);
        txtTotal.setText("" + total);
        txtPajak.setText("" + pajak);
        txtBayar.setText("" + bayar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboMakan = new javax.swing.JComboBox<>();
        txtQtyMakan = new javax.swing.JTextField();
        txtHargaMakan = new javax.swing.JTextField();
        txtSubtotalMakan = new javax.swing.JTextField();
        btnTbhMakan = new javax.swing.JButton();
        cboMinum = new javax.swing.JComboBox<>();
        txtQtyMinum = new javax.swing.JTextField();
        txtHargaMinum = new javax.swing.JTextField();
        txtSubtotalMinum = new javax.swing.JTextField();
        btnTbhMinum = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableData = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtPajak = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtBayar = new javax.swing.JTextField();
        btnBayar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cboMakan.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        cboMakan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih-", "Ayam Pop", "Ayam Bakar", "Rendang Daging", "Dendeng Balado", "Sop Iga Sapi" }));
        cboMakan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMakanActionPerformed(evt);
            }
        });

        txtQtyMakan.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtQtyMakan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtyMakanActionPerformed(evt);
            }
        });
        txtQtyMakan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQtyMakanKeyTyped(evt);
            }
        });

        txtHargaMakan.setEditable(false);
        txtHargaMakan.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        txtSubtotalMakan.setEditable(false);
        txtSubtotalMakan.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        btnTbhMakan.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnTbhMakan.setText("Tambah");
        btnTbhMakan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTbhMakanActionPerformed(evt);
            }
        });

        cboMinum.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        cboMinum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih-", "Juice Jeruk", "Juice Sirsak", "Juice Guava", "Juice Melon", "Juice Mangga" }));
        cboMinum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMinumActionPerformed(evt);
            }
        });
        cboMinum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cboMinumKeyTyped(evt);
            }
        });

        txtQtyMinum.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        txtHargaMinum.setEditable(false);
        txtHargaMinum.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        txtSubtotalMinum.setEditable(false);
        txtSubtotalMinum.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        btnTbhMinum.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnTbhMinum.setText("Tambah");
        btnTbhMinum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTbhMinumActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel8.setText("Sub Total :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel7.setText("Harga :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel6.setText("Qty :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel5.setText("Menu Minuman :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel4.setText("Sub Total :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setText("Harga :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("Qty :");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel1.setText("Menu Makanan :");

        tableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Menu", "Qty", "Harga", "Sub Total"
            }
        ));
        jScrollPane1.setViewportView(tableData);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel9.setText("Total :");

        txtTotal.setEditable(false);
        txtTotal.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel10.setText("Pajak (10%) :");

        txtPajak.setEditable(false);
        txtPajak.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel11.setText("Bayar :");

        txtBayar.setEditable(false);
        txtBayar.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        btnBayar.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnBayar.setText("Bayar");
        btnBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBayarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnTbhMakan, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cboMinum, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtQtyMakan)
                            .addComponent(txtHargaMakan)
                            .addComponent(txtSubtotalMakan)
                            .addComponent(txtHargaMinum)
                            .addComponent(txtSubtotalMinum)
                            .addComponent(txtQtyMinum)
                            .addComponent(cboMakan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(btnTbhMinum, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPajak)
                            .addComponent(txtBayar, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                            .addComponent(txtTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                            .addComponent(btnBayar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cboMakan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtQtyMakan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtHargaMakan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtSubtotalMakan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(btnTbhMakan)
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cboMinum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPajak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBayar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtQtyMinum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtHargaMinum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtSubtotalMinum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTbhMinum)))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTbhMakanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTbhMakanActionPerformed
        if (cekKosong(true) == false) {
            String menuItem = cboMakan.getSelectedItem().toString();
            if (cekDataTabel(menuItem) == false) {
                int hrg = Integer.parseInt(txtHargaMakan.getText());
                int kuantiti = Integer.parseInt(txtQtyMakan.getText());
                txtSubtotalMakan.setText("" + (hrg * kuantiti));

                menu.add(menuItem);
                harga.add(txtHargaMakan.getText());
                qty.add(txtHargaMakan.getText());
                subtotal.add(txtHargaMakan.getText());

                setTabel();
            }
        }
    }//GEN-LAST:event_btnTbhMakanActionPerformed

    private void btnTbhMinumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTbhMinumActionPerformed
        if (cekKosong(false) == false) {
            String menuItem = cboMinum.getSelectedItem().toString();
            if (cekDataTabel(menuItem) == false) {
                int hrg = Integer.parseInt(txtHargaMinum.getText());
                int kuantiti = Integer.parseInt(txtQtyMinum.getText());
                txtSubtotalMinum.setText("" + (hrg * kuantiti));

                menu.add(menuItem);
                harga.add(txtHargaMinum.getText());
                qty.add(txtHargaMinum.getText());
                subtotal.add(txtHargaMinum.getText());

                setTabel();
            }
        }
    }//GEN-LAST:event_btnTbhMinumActionPerformed

    private void btnBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBayarActionPerformed
        JOptionPane.showMessageDialog(null, "Terima Kasih atas kunjungannya");
        cboMakan.setSelectedIndex(0);
        txtQtyMakan.setText("0");
        txtHargaMakan.setText("0");
        txtSubtotalMakan.setText("0");

        cboMinum.setSelectedIndex(0);
        txtQtyMinum.setText("0");
        txtHargaMinum.setText("0");
        txtSubtotalMinum.setText("0");

        menu.clear();
        harga.clear();
        qty.clear();
        subtotal.clear();

        setTabel();

    }//GEN-LAST:event_btnBayarActionPerformed

    private void cboMakanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMakanActionPerformed
        setHargaMakanan();
    }//GEN-LAST:event_cboMakanActionPerformed

    private void cboMinumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMinumActionPerformed
        setHargaMinuman();
    }//GEN-LAST:event_cboMinumActionPerformed

    private void txtQtyMakanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtyMakanActionPerformed
    }//GEN-LAST:event_txtQtyMakanActionPerformed

    private void txtQtyMakanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtyMakanKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_txtQtyMakanKeyTyped

    private void cboMinumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboMinumKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_cboMinumKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kasir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBayar;
    private javax.swing.JButton btnTbhMakan;
    private javax.swing.JButton btnTbhMinum;
    private javax.swing.JComboBox<String> cboMakan;
    private javax.swing.JComboBox<String> cboMinum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableData;
    private javax.swing.JTextField txtBayar;
    private javax.swing.JTextField txtHargaMakan;
    private javax.swing.JTextField txtHargaMinum;
    private javax.swing.JTextField txtPajak;
    private javax.swing.JTextField txtQtyMakan;
    private javax.swing.JTextField txtQtyMinum;
    private javax.swing.JTextField txtSubtotalMakan;
    private javax.swing.JTextField txtSubtotalMinum;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
